bilbulat = 10 # integer
bilfloat = 15.0 # float
bilstr = "Myname Valdo_Mediatech" # string
bilcomplex = 1j # complex
billist = ["Angela","Gerungan","Valdo"] # list
biltuple = ("WhiteHat","BlackHat") # tuple
bilrange = range(5) # range
bildict = {"My name":" Rivaldo ","Myage  ": 23} # dict
bilset = {"Bogar","Rivaldo","Angela"} # frozenset
bilbool = True # bool
bilbytes = b"Valdo_GameDev" # byte
bilByteTernary = bytearray(5) # bytearray
# frozetset belum terlalu mengerti
bilmemorybyte = memoryview(bytes(5))
bilnone = None

print("Integer = ", bilbulat, type(bilfloat))
print("Float = ", bilfloat, type(bilfloat))
print("String = ", bilstr, type(bilstr))
print("List = ", billist, type(billist))
print("Tuple = ", biltuple, type(biltuple))
print("Range = ", bilrange, type(bilrange))
print("Dict = ", bildict, type(bildict))
print("Set = ", bilset, type(bilset))
print("Set = ", bilbool, type(bilbool))
print("Set = ", bilbytes, type(bilbytes))
print("Set = ", bilByteTernary, type(bilByteTernary))
print("Set = ", bilmemorybyte, type(bilmemorybyte))
print("Set = ", bilnone, type(bilnone))
